### Create New Product
POST http://localhost:3000/products
Content-Type: application/json

{
    "productid": 101,
    "name": "iPhone 15",
    "brand": "Apple",
    "price": 80000
}

### Read All Products
GET http://localhost:3000/products

### Read Products By Brand
GET http://localhost:3000/products/brand/Apple

### Update Product
PUT http://localhost:3000/products/101
Content-Type: application/json

{
    "productid": 101,
    "name": "iPhone 15 Pro",
    "brand": "Apple",
    "price": 120000
}

### Delete Product
DELETE http://localhost:3000/products/101